language: node_js
node_js:
    - "10"
    - "8"
    - "6"

before_install:
  - npm install -g greenkeeper-lockfile
install: npm install

before_script: greenkeeper-lockfile-update
script: "npm test"
after_script: greenkeeper-lockfile-upload

after_success: "npm run coverage"

